version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ecoride_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environnement:
      DOCKER_ENV: "true"
      MONGO_URI: ${MONGO_URI}

  db:
    image: mysql:8.0
    container_name: ecoride_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
